[package]
name = "runtime_cfparser"
version = "0.1.0"
edition = "2021"
authors = ["The Caffeine Project Contributors"]
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.79"
mutf8 = { version = "0.5.0", default-features = false }
nom = "7.1.3"
